<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Simple HttpErrorPages | MIT X11 License | https://github.com/AndiDittrich/HttpErrorPages -->

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <title>Algo deu errado | <?php echo $v_code; ?> - <?php echo $v_title; ?></title>

    <style type="text/css"><?php echo $css; ?></style>
</head>

<body>
    <div class="cover">
        <h1><big>ERRO<?php echo $v_code; ?></big></h1>
        <h1><?php echo $v_title; ?></h1>
        <p class="lead"><?php echo $v_message; ?></p>
        <div class="anchor">
            <a class="btn" href="http://dev05.devcoffee.com.br">Ir para a página inicial</a>
        </div>
    </div>
    
    

    <?php if (!empty($v_footer)){ ?>
    <footer>
        <p><?php echo $v_footer; ?></p>
    </footer>
    <?php } ?>
</body>
</html>
